version: '3'

services:
  db:
    image: postgres:10.3
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
  app:
    image: 'app'
    build:
      context: ../dockers/app
    ports:
      - "${APP_EXTERNAL_PORT}:8000"
    env_file:
      - .env
    volumes:
      - '../app/:/app'
    depends_on:
      - db
